[build]
  # Directorio de publicación (donde están los archivos del sitio)
  publish = "."
  
  # Comando de construcción para inyectar variables de entorno
  command = "node build-env.js"

[build.environment]
  # Variables de entorno si las necesitas
  NODE_VERSION = "18"
  # Variables de Supabase para producción
  VITE_SUPABASE_URL = "https://ggzyqssptaonmwxoaedw.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnenlxc3NwdGFvbm13eG9hZWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDc4MjYsImV4cCI6MjA3MjQyMzgyNn0.u_EpXzGNFqD_M_DQ2mnofkqCoSdzDjXv09-norDHpKo"

# Configuración para manejar errores 404
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Configuración de redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Configuración de headers para mejor rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"